### ISSUE TITLE
Initial comment in table definition is associated with (non-existent) return value

### ISSUE THREAD

**Issue by ladc** [lunarmodules/ldoc#132] opened 2013-12-16 16:36 UTC
I encountered an error due to the use of (undeclared global) `quote()` instead of `tools.quote()` in https://github.com/stevedonovan/LDoc/blob/master/ldoc/doc.lua#L919

The reason that this error was triggered in the first place, was because I had an initial comment in the table definition, like so:

``` lua
--- Two tables.

--- Implicit table
local a = {
  x = 1, -- x value
  y = 2, -- y value
}

--- Another implicit table 
local b = {
  -- letters
  z = 3, -- z value
  -- here be dragons
  dragons = true, -- present
  reptiles = true, -- etc
}

-- @export
return {a=a,b=b}
```

If I understand correctly, the comment `-- letters` here is recognized as the comment for a return value, which a table obviously lacks. Is this a bug, or should I just not do that? In any case, I think I've missed how to make LDoc ignore a comment.

**Comment by alerque** [comment] 2023-05-03 08:49
Confirmed still an issue. Contributions welcome if anybody wants to tackle this!

**Comment by alerque** [comment] 2023-05-03 10:02
Duplicate of #101.

**Closed by alerque** 2023-05-03 10:02 UTC
Labels: duplicate
