### ISSUE TITLE
Disable backtick references

### ISSUE THREAD

**Issue by craigbarnes** [lunarmodules/ldoc#100] opened 2013-10-04 21:10 UTC
Is there any way to disable automatic linking of "recognized" words inside backticks?

I have a [readme](http://cra.igbarn.es/projects/lua-gumbo/topics/README.md.html) file that contains a few occurrences of ``type`` and LDoc is turning them into unwanted links to the Lua reference manual.

**Edit**: the readme link above no longer demonstrates what I describe, since I did a little `sed` post-processing.

**Comment by alerque** [comment] 2023-05-03 08:30
Duplicate of #81, still not addressed.

**Comment by alerque** [comment] 2023-05-03 08:32
Correction, #81 is related but would only be resolved by specific filtering of backticks.

In the mean time there **was** a new config option added to disable them completely as this issue requested, set `backtick_references = false` in your config.

**Closed by alerque** 2023-05-03 08:32 UTC
Labels: duplicate
